### ISSUE TITLE
Error after upgrade Angular to 9.1

### ISSUE THREAD

**Issue by lippomano** [shipshapecode/angular-shepherd#207]
Just updated Angular to 9.1.0 and I have this error when I run ng serve and build.

> ERROR in node_modules/angular-shepherd/lib/shepherd.service.d.ts:64:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).
    64     static ɵfac: i0.ɵɵFactoryDef<ShepherdService>;

In Angular/core/core.d.ts now there is this declaration:
`export declare type ɵɵFactoryDef<T, CtorDependencies extends CtorDependency[]> = () => T;`

**Comment by rwwagner90** [comment]
Angular is incredibly bad at compatibility. Libraries seem to only be able to support one exact Angular version at a time. This will likely go away if we update some deps.

**Comment by lippomano** [comment]
In another library I found this line maybe it helps:
`static ɵfac: ɵngcc0.ɵɵFactoryDef<Ng2TelInput, never>;`

if I use it on your code it works.

**Comment by rwwagner90** [comment]
Not sure what you mean. We don't have anything like that, that I know of. Open to suggestions!

**Comment by gmisiolek** [comment]
Just need to update angular with `ng update @angular/cli @angular/core` build and release a new version. That should work and fix missing second argument of `ɵɵFactoryDef`.

**Comment by rwwagner90** [comment]
@gmisiolek yeah, I was saying we aren't using anything like you mentioned, but for sure updating deps would fix things. I was saying that here https://github.com/shipshapecode/angular-shepherd/issues/207#issuecomment-606613117. We will work on updating deps soon hopefully.

**Comment by jotae1e** [comment]
Can you take a look to this link?

https://github.com/angular/angular/issues/35291#issuecomment-585092417

He saids that it's a problem with the build of some libraries, that compile with Ivy support by default.

**Comment by drenda** [comment]
Hi @rwwagner90, do you have any ETA for the new release? Thanks

**Comment by rwwagner90** [comment]
@drenda there was a new release already.

**Comment by drenda** [comment]
Oh sorry I didn't see it because they were hidden in Github.
